### ISSUE TITLE
How should we handle exceptional scenario with this library

### ISSUE THREAD

**Issue by lahirug** [scala/scala-async#137]
I can see that cannot put try/finally block, how should I handle that ?

**Comment by pkolaczk** [comment]
Adding to this question. How do I handle a failed Future under await?
```scala
async {
  val result = await { thisMayReturnFailedFuture }
}
```

Putting it into a try/catch block is not allowed :(

**Comment by SethTisue** [comment]
arguably a duplicate of #76
