### ISSUE TITLE
Frontend developing: transform Future[T] in T

### ISSUE THREAD

**Issue by monmic** [scala/scala-async#148]
val router =
    async {
      val f1 = AjaxClient[API].allowed().call()
      val result = await(f1)
      Router(baseUrl, Page(result).config)
    }

Await.result(awaitable, duration) on scalajs does not work.. how could I use in scalajs the val router?

**Comment by SethTisue** [comment]
closing as stale, and because I suspect this isn't properly an issue with scala-async in particular, but `Future` in general
