### ISSUE TITLE
release for Scala 2.13.0-M2

### ISSUE THREAD

**Issue by SethTisue** [scala/scala-async#174]
#173 is merged and has all the version number bumps, but:

as for actually publishing for Scala 2.13.0-M2, that's a bit tricky since that PR itself contains the sbt-scala-module version bump needed in order to republish an existing module version for a new Scala version

I see two options:

1) go ahead and burn a version number on it
2) backport just the sbt-scala-module version bump, branching the backport off the existing tag

I think I'm going to go ahead and burn a version number on it, since it doesn't really cost anything. and since it's actually possible, if unlikely, for there to be some regression associated with the plugin version bump

**Comment by retronym** [comment]
Publishing 0.9.7 via https://github.com/scala/scala-async/releases/tag/v0.9.7. I'm happy to have the recently merged performance improvements in place.

**Comment by retronym** [comment]
Released to Sonatype.

![image](https://user-images.githubusercontent.com/65551/29056886-ba941916-7c49-11e7-9098-0a4d0cc4bb29.png)
