### ISSUE TITLE
Question: if i use debugger with async would the debugger stop on each line as in golang?

### ISSUE THREAD

**Issue by tomer-ben-david** [scala/scala-async#175]
One of the benefits as i see in golang is that if i debug the code I can do stepover -> stepover and see the actual execution.  where in scala futures I need to put breakpoints inside the future results.  if i use this async would it be possible then to use the debugger and see this code as step by step? coming to think of it, as the execution will pass on immediately to the line after the async block it would not be as in golang, as the async block is on one thread and the lines of code after the async block are in a different thread, so i cannot do the same nice debugging as in golang where i just execute it line by line, is my analysis correct?

**Comment by lrytz** [comment]
Scala IDE and IntelliJ have "asynch" modes in their debuggers (http://scala-ide.org/docs/current-user-doc/features/async-debugger/index.html, https://blog.jetbrains.com/idea/2017/02/intellij-idea-2017-1-eap-extends-debugger-with-async-stacktraces/)

**Comment by tomer-ben-david** [comment]
thanks
