### ISSUE TITLE
is the project dead or stale?

### ISSUE THREAD

**Issue by sergiorussia** [scala/scala-async#184]
hi. i really like scala-async, but releases are very rare, there are a lot of issues and no upcoming [big] features afaik. library is easy to use for simple cases, but there are a lot of inconveniences like:

- cannot use async-await with try-catch
- cannot use async-await with `for` [comprehensions] (eg for item in collection do await)
- cannot use async-await with pattern matching (eg someOption match case Some case None...)
- etc etc

we have a lot of concurrent code in our project, but code with plain Futures is very noisy, pretty hard to read and maintain (even with for-compr).

do you have any plans for any features in the nearest future? or maybe there are another similar/alternative projects that i dont know about and which are worth to look at?

**Comment by retronym** [comment]
We've sketched out designs for many of those features, but don't have resources to implement them in the near term. Much of the work on async has been sponsored by a commercial user, and I am hopeful that they will be able to sponsor work on some of those features once some higher priority items are crossed off their list :)
