### ISSUE TITLE
Cross-publish for Scala.JS?

### ISSUE THREAD

**Issue by alexarchambault** [scala/scala-async#248]
It seems the classes of scala-async are now required at runtime when using `async` / `await`. This breaks Scala.JS projects using scala-async, as it's not cross-published for Scala.JS.

See [this test project](https://github.com/alexarchambault/scala-async-scala-js) for a reproduction, or https://github.com/coursier/coursier/pull/1843. The test project README details the linking error one runs into during `fastOptJS`.

**Comment by SethTisue** [comment]
In the Scala modules generally, we have gladly merged pull requests adding Scala.js and/or Scala Native cross-builds when they have been submitted by the community. It isn't something we've normally tackled ourselves.

**Comment by OndrejSpanel** [comment]
PR submitted.

**Comment by SethTisue** [comment]
publishing ticket: #276
