### ISSUE TITLE
await() on already-completed future could return value synchronously

### ISSUE THREAD

**Issue by danarmak** [scala/scala-async#73]
await(future) always compiles to future.onComplete(...), even if the future is already completed. (I think so based on the output of `scalac --Ymacro-debug-lite` in the 2.10 branch.) Why not return the value synchronously if it is already available? 

Here's a simple implementation as a macro wrapping await():

```
  def fastAwait[T](fut: Future[T]): T = macro fastAwaitImpl[T]

  def fastAwaitImpl[T: c.WeakTypeTag](c: Context)(fut: c.Expr[Future[T]]): c.Expr[T] = {
    import c.universe._
    val tree =  q"{ val f = $fut; if (f.isCompleted) f.value.get.get else await(f) }"
    c.Expr[T](tree)
  }
```

I have code that passes very large amounts of short-lived Futures around. Many of these are already completed when awaited. This optimization helps (from initial tests) and I'm considering using it in my code - is there any reason not to do this?

**Comment by scott-abernethy** [comment]
@retronym Fantastic. I just tested out the 0.9.3 snapshot and this little optimisation gives a significant performance improvement for my channels implementation (it often awaits on essentially Future.successful(x)).

Over 3x faster on a sample test (410K messages/sec now compared to 120K messages/sec prior to the patch.

Thanks!
